# Generic helm chart configurations

##### BEGIN - Tekton Triggers duty #####
image:
  repository: ""
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
##### END - Tekton Triggers duty #####


  
  
##### BEGIN - Developer team duty #####
replicaCount: 1  
  
service:
  type: ClusterIP
  port: 80

resources: 
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

containerPort: 8080

readinessProbe:
#  failureThreshold: 5
#  httpGet:
#    path: /api/health
#    port: http
#    scheme: HTTP
#  initialDelaySeconds: 60
#  periodSeconds: 10
#  successThreshold: 1
#  timeoutSeconds: 1


livenessProbe: 
#  failureThreshold: 5
#  httpGet:
#    path: /api/health
#    port: http
#    scheme: HTTP
#  initialDelaySeconds: 60
#  periodSeconds: 10
#  successThreshold: 1
#  timeoutSeconds: 1
  
  
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60


## Application configmap 
configMap:
  enabled: false
  name: configmap-example
  keys: 
   #logFile: /tmp/output.log
   #logSize: 10m
   
## Linkedsecrets
linkedsecrets:
  enabled: false
  name: myapp-linkedsecrets
  spec:
    provider: Azure # (GCP | AWS | Azure | IBM)
    providerDataFormat: JSON # (JSON | PLAIN)
    ## providerOptions fields depend on what provider you have chosen.
    ## Please check https://kubeideas.github.io/linkedsecrets/#cloud-provider-specific-instructions for details.
    providerOptions: 
      keyvault: linkedsecret
      secret: opaque-secret-json
    secretName: myapp-kubernetes-secret
    schedule: "\"@every 10m\""
    ## deployment name for rollout update if secret has changed
    #deployment: myapp 

  
##### END - Developer team duty #####  






##### BEGIN - Devops team duty #####

imagePullSecrets: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

## NGINX Ingress controller
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/issuer: "nameOfIssuer"
    # cert-manager.io/cluster-issuer: "nameOfClusterIssuer"
  hosts: 
    - host: chart-example.local
      paths: 
        - /     
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


## istio service mesh
istio:
  enabled: false
  dnsNames: 
    - chart-example.local
  certManager:
    enabled: false
    issuer:
      name: letsencrypt-prod
      kind: ClusterIssuer
  gateway:
    enabled: false
    httpsRedirect: false
    http: false
    ## true =  Set credentialName with the secret name to store private key and certificate chain (letsencrypt|imported certs)
    ## false = private key and certificate chain is expected to be attached to Load Balancer
    localCert: false
    credentialName: mydomain-tls
  virtualservice:
    gateways: 
      - istio-system/my-gateway
    paths: 
      - /
    

nodeSelector: {}

tolerations: []

affinity: {}

##### END - Devops team duty #####
