apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "generic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        releaseTimestamp: {{ now | date "2006-01-02T15:04:05Z" | quote }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "generic.selectorLabels" . | nindent 8 }}
        {{- include "generic.istioLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "generic.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "generic.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # configMap and secret as environment variables
          envFrom:
            {{- if and (.Values.configMap.enabled) (not .Values.configMap.volume.enabled) }}
            - configMapRef:
                name: {{ .Values.configMap.name }}
            {{- end }}
            {{- if and (.Values.secret.enabled) (not .Values.secret.volume.enabled) }}
            - secretRef:
                name: {{ .Values.secret.name}}
            {{- end }}                
            {{- if and (.Values.linkedsecrets.enabled) (not .Values.linkedsecrets.volume.enabled) }}
            - secretRef:
                name: {{ .Values.linkedsecrets.secretName}}                
            {{- end }} 
          # configMap and secret as volumes
          volumeMounts:
          {{- if and .Values.configMap.enabled .Values.configMap.volume.enabled }}  
          - name: {{ .Values.configMap.name }}-volume
            mountPath: {{ .Values.configMap.volume.mountPath }}  
          {{- end }}
          {{- if and .Values.secret.enabled .Values.secret.volume.enabled }}
          - name: {{ .Values.secret.name}}-volume
            mountPath: {{ .Values.secret.volume.mountPath }}      
          {{- end }}       
          {{- if and .Values.linkedsecrets.enabled .Values.linkedsecrets.volume.enabled }}
          - name: {{ .Values.linkedsecrets.secretName}}-volume
            mountPath: {{ .Values.linkedsecrets.volume.mountPath }}      
          {{- end }}                   
          ports:
            - name: http
              containerPort: {{ .Values.containerPort}}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if and .Values.configMap.enabled .Values.configMap.volume.enabled }} 
        - name: {{ .Values.configMap.name }}-volume
          configMap:
            name: {{ .Values.configMap.name }} 
        {{- end }}     
        {{- if and .Values.secret.enabled .Values.secret.volume.enabled }} 
        - name: {{ .Values.secret.name }}-volume
          secret:
            secretName: {{ .Values.secret.name }} 
        {{- end }}       
        {{- if and .Values.linkedsecrets.enabled .Values.linkedsecrets.volume.enabled }} 
        - name: {{ .Values.linkedsecrets.secretName }}-volume
          secret:
            secretName: {{ .Values.linkedsecrets.secretName }} 
        {{- end }}                  
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}