{{- if .Values.linkedsecrets.enabled -}}
apiVersion: security.kubeideas.io/v1
kind: LinkedSecret
metadata:
  annotations:
    "helm.sh/hook": pre-install
  name: {{ .Values.linkedsecrets.name }}
spec:
  provider: {{ .Values.linkedsecrets.provider }}
  providerDataFormat: {{ .Values.linkedsecrets.providerDataFormat }}
  providerOptions:
    {{- toYaml .Values.linkedsecrets.providerOptions | nindent 4 }}
  secretName: {{ .Values.linkedsecrets.secretName }}
  schedule: {{ .Values.linkedsecrets.schedule }}
  deployment: {{ .Values.linkedsecrets.deployment }}
{{- end }}
