{{- if .Values.linkedsecrets.enabled -}}
apiVersion: security.kubeideas.io/v1
kind: LinkedSecret
metadata:
  name: {{ .Values.linkedsecrets.name }}
spec:
  {{- toYaml .Values.linkedsecrets.spec | nindent 2 }}
{{- end }}