{{- if .Values.secret.enabled -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := .Values.secret.keys }}
  {{ $k }}: {{ $v | b64enc}}
  {{- end }}

{{- end }}  