{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }} 
spec:
  hosts:
  {{- range .Values.istio.dnsNames }}
  - {{ . | quote }}
  {{- end }}
  gateways:
  {{ if .Values.istio.virtualservice.gateways }}
  {{- range .Values.istio.virtualservice.gateways }}
  - {{ . | quote }}
  {{- end }}
  {{ else }}
  - {{ include "generic.fullname" . }}
  {{- end }}
  http:
  - match:
    {{- range .Values.istio.virtualservice.paths }}
    - uri:
        prefix: {{ . | quote }}
    {{- end }} 
    route:
    - destination:
        host: {{ include "generic.serviceClusterFQDN" . }}
        port:
          number: {{ .Values.service.port }} 
{{- end }}